/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",

    ],
    theme: {
        screens: {
            xxs: '320px',
            xs: '420px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1536px',
            '3xl': '2536px',
        },
        extend: {
            colors: {
                grayer: "#fafafa",
                blackish: "#030229",
                text: "#030229",
                mediumslateblue: "#605bff",
                darkslateblue: "#382c7c",
                white: "#fff",
                redish: "#BB4430",
                red: {
                    light: '#FFF0F4',
                    error: '#EB0B00'
                },
                text: "#030229",
                mediumslateblue: "#605bff",
                darkslateblue: "#382c7c",
                white: "#fff",
                blue: "rgba(33, 0, 235, 0.06)",
                darkslategray: "#333",
                linen: "rgba(245, 238, 229, 0)",
                mediumblue: "rgba(103, 0, 235, 0.18)",
                lavender: "rgba(235, 233, 247, 0)",
                black: "#000",
                aliceblue: "#e4ecf3",
                dimgray: {
                    "100": "#5a5a5a",
                    "200": "#4f4f4f",
                },
                lightslategray: "#919dab",
                darkgray: "#9f9f9f",
                lightgray: "#d5d5d5",
            },
            textColor: {
                unselected: "#97a3bb",
                selected: "#382C7C",
                ultraMarine: "#030229",
                card: "rgba(255, 255, 255, 0.39)",
                green: "#439A86",
            },
            backgroundColor: {
                selected: "#382C7C",
                unselected: "#97a3bb",
                dashboard: "#FAFAFB",
                cardBlue: "#0D3151",
                red: {
                    light: '#FFF0F4',
                    error: '#EB0B00'
                },
                card: "linear-gradient(180deg, #0D3151 0%, #0D3151 100%)",
            },
            boxShadowColor: {
                selected: "#382C7C",
            },
            spacing: {},
            fontFamily: {
                nunito: "Nunito",
                quicksand: "Quicksand",
                mitr: "Mitr",
                roboto: "Roboto",
                inter: "Inter",
            },
        },
        fontSize: {
            md: '27.2px',
            xxs: '10px',
            xs: '12px',
            sm: '14px',
            tiny: '14px',
            base: '16px',
            lg: '18px',
            xl: '20px',
            '2xl': '24px',
            '3xl': '30px',
            '4xl': '36px',
            '5xl': '48px',
            '6xl': '64px',
            '7xl': '80px',
            "5xl-1": "24.1px",
            "xl-2": "20.2px",
            "lg-8": "18.8px",
            "sm-7": "13.7px",
            inherit: "inherit",
        },
        // fontWeight: {
        //     100: 100,
        //     200: 200,
        //     300: 300,
        //     400: 400,
        //     500: 500,
        //     600: 600,
        //     700: 700,
        //     800: 800,
        //     900: 900
        // },
    },
    corePlugins: {
        preflight: false,
    },
};
