export {default as Logo} from '@public/assets/logo/vestra.svg';
export {default as LogoIcon} from '@public/assets/logo/vestra.png';
export {default as DashboardIcon} from '@public/assets/icons/Category.svg';
export {default as UsersIcon} from '@public/assets/icons/Group.svg';
export {default as TransactionsIcon} from '@public/assets/icons/Chart.svg';
export {default as PaymentsIcon} from '@public/assets/icons/transfer.svg';
export {default as DisputeLogsIcon} from '@public/assets/icons/supervised_user_circle.svg';
export {default as NotificationIcon} from '@public/assets/icons/Notification.svg';
export {default as SettingsIcon} from '@public/assets/icons/Setting.svg';
export {default as LogoutIcon} from '@public/assets/icons/Logout.svg';
export {default as MigrationIcon} from '@public/assets/icons/exchange 1.svg';
// export {default as DashboardIconActive} from '@public/assets/icons/Category.png';
// export {default as ProfileImage2} from '@public/assets/icons/dummy-profile.png';
export {default as ProfileImage3} from '@public/assets/icons/dummy-profile[1].png';
export {default as CardLogo} from '@public/assets/logo/vestra-card.png';
export {default as Cloud} from '@public/assets/utils/cloud.png';
export {default as MasterCard} from '@public/assets/logo/mastercard.svg';
export {default as DivisionLine} from '@public/assets/utils/Line.svg';
export {default as Delimiter} from '@public/assets/utils/LineDelimiter.svg';
export {default as Loader} from '@public/assets/utils/loadingAnimation.json';
export {default as PenIcon} from '@public/assets/utils/pen.svg';
export {default as LineHorizontal} from '@public/assets/utils/LineHorizontal.svg';
export {default as UploadFile} from '@public/assets/svg/uploadFile.svg';
export {default as UploadFileSmall} from '@public/assets/svg/uploadFileSmall.svg';