export const BanksJson = [
    { id: "1", value: "Access Bank", name: "Access Bank", code: "044" },
    { id: "2", value: "Citibank", name: "Citibank", code: "023" },
    { id: "3", value: "Diamond Bank", name: "Diamond Bank", code: "063" },
    { id: "4", value: "Dynamic Standard Bank", name: "Dynamic Standard Bank", code: "" },
    { id: "5", value: "Ecobank Nigeria", name: "Ecobank Nigeria", code: "050" },
    { id: "6", value: "Fidelity Bank Nigeria", name: "Fidelity Bank Nigeria", code: "070" },
    { id: "7", value: "First Bank of Nigeria", name: "First Bank of Nigeria", code: "011" },
    { id: "8", value: "First City Monument Bank", name: "First City Monument Bank", code: "214" },
    { id: "9", value: "Guaranty Trust Bank", name: "Guaranty Trust Bank", code: "058" },
    { id: "10", value: "Heritage Bank Plc", name: "Heritage Bank Plc", code: "030" },
    { id: "11", value: "Jaiz Bank", name: "Jaiz Bank", code: "301" },
    { id: "12", value: "Keystone Bank Limited", name: "Keystone Bank Limited", code: "082" },
    { id: "13", value: "Providus Bank Plc", name: "Providus Bank Plc", code: "101" },
    { id: "14", value: "Polaris Bank", name: "Polaris Bank", code: "076" },
    { id: "15", value: "Stanbic IBTC Bank Nigeria Limited", name: "Stanbic IBTC Bank Nigeria Limited", code: "221" },
    { id: "16", value: "Standard Chartered Bank", name: "Standard Chartered Bank", code: "068" },
    { id: "17", value: "Sterling Bank", name: "Sterling Bank", code: "232" },
    { id: "18", value: "Suntrust Bank Nigeria Limited", name: "Suntrust Bank Nigeria Limited", code: "100" },
    { id: "19", value: "Union Bank of Nigeria", name: "Union Bank of Nigeria", code: "032" },
    { id: "20", value: "United Bank for Africa", name: "United Bank for Africa", code: "033" },
    { id: "21", value: "Unity Bank Plc", name: "Unity Bank Plc", code: "215" },
    { id: "22", value: "Wema Bank", name: "Wema Bank", code: "035" },
    { id: "23", value: "Zenith Bank", name: "Zenith Bank", code: "057" }
]