export const CountriesJson = [ 
    // {value: 'Afghanistan', name: 'Afghanistan', id: 'AF'}, 
    {value: 'Åland Islands', name: 'Åland Islands', id: 'AX'}, 
    {value: 'Albania', name: 'Albania', id: 'AL'}, 
    {value: 'Algeria', name: 'Algeria', id: 'DZ'}, 
    {value: 'American Samoa', name: 'American Samoa', id: 'AS'}, 
    {value: 'AndorrA', name: 'AndorrA', id: 'AD'}, 
    {value: 'Angola', name: 'Angola', id: 'AO'}, 
    {value: 'Anguilla', name: 'Anguilla', id: 'AI'}, 
    {value: 'Antarctica', name: 'Antarctica', id: 'AQ'}, 
    {value: 'Antigua and Barbuda', name: 'Antigua and Barbuda', id: 'AG'}, 
    {value: 'Argentina', name: 'Argentina', id: 'AR'}, 
    {value: 'Armenia', name: 'Armenia', id: 'AM'}, 
    {value: 'Aruba', name: 'Aruba', id: 'AW'}, 
    {value: 'Australia', name: 'Australia', id: 'AU'}, 
    {value: 'Austria', name: 'Austria', id: 'AT'}, 
    {value: 'Azerbaijan', name: 'Azerbaijan', id: 'AZ'}, 
    {value: 'Bahamas', name: 'Bahamas', id: 'BS'}, 
    {value: 'Bahrain', name: 'Bahrain', id: 'BH'}, 
    {value: 'Bangladesh', name: 'Bangladesh', id: 'BD'}, 
    {value: 'Barbados', name: 'Barbados', id: 'BB'}, 
    // {value: 'Belarus', name: 'Belarus', id: 'BY'}, 
    {value: 'Belgium', name: 'Belgium', id: 'BE'}, 
    {value: 'Belize', name: 'Belize', id: 'BZ'}, 
    {value: 'Benin', name: 'Benin', id: 'BJ'}, 
    {value: 'Bermuda', name: 'Bermuda', id: 'BM'}, 
    {value: 'Bhutan', name: 'Bhutan', id: 'BT'}, 
    {value: 'Bolivia', name: 'Bolivia', id: 'BO'}, 
    {value: 'Bosnia and Herzegovina', name: 'Bosnia and Herzegovina', id: 'BA'}, 
    {value: 'Botswana', name: 'Botswana', id: 'BW'}, 
    {value: 'Bouvet Island', name: 'Bouvet Island', id: 'BV'}, 
    {value: 'Brazil', name: 'Brazil', id: 'BR'}, 
    {value: 'British Indian Ocean Territory', name: 'British Indian Ocean Territory', id: 'IO'}, 
    {value: 'Brunei Darussalam', name: 'Brunei Darussalam', id: 'BN'}, 
    {value: 'Bulgaria', name: 'Bulgaria', id: 'BG'}, 
    {value: 'Burkina Faso', name: 'Burkina Faso', id: 'BF'}, 
    // {value: 'Burundi', name: 'Burundi', id: 'BI'}, 
    {value: 'Cambodia', name: 'Cambodia', id: 'KH'}, 
    {value: 'Cameroon', name: 'Cameroon', id: 'CM'}, 
    {value: 'Canada', name: 'Canada', id: 'CA'}, 
    {value: 'Cape Verde', name: 'Cape Verde', id: 'CV'}, 
    {value: 'Cayman Islands', name: 'Cayman Islands', id: 'KY'}, 
    // {value: 'Central African Republic', name: 'Central African Republic', id: 'CF'}, 
    {value: 'Chad', name: 'Chad', id: 'TD'}, 
    {value: 'Chile', name: 'Chile', id: 'CL'}, 
    // {value: 'China', name: 'China', id: 'CN'}, 
    {value: 'Christmas Island', name: 'Christmas Island', id: 'CX'}, 
    {value: 'Cocos (Keeling) Islands', name: 'Cocos (Keeling) Islands', id: 'CC'}, 
    {value: 'Colombia', name: 'Colombia', id: 'CO'}, 
    {value: 'Comoros', name: 'Comoros', id: 'KM'}, 
    {value: 'Congo', name: 'Congo', id: 'CG'}, 
    // {value: 'Congo, The Democratic Republic of the', name: 'Congo, The Democratic Republic of the', id: 'CD'}, 
    {value: 'Cook Islands', name: 'Cook Islands', id: 'CK'}, 
    {value: 'Costa Rica', name: 'Costa Rica', id: 'CR'}, 
    {value: 'Cote D\'Ivoire', name: 'Cote D\'Ivoire', id: 'CI'}, 
    {value: 'Croatia', name: 'Croatia', id: 'HR'}, 
    // {value: 'Cuba', name: 'Cuba', id: 'CU'}, 
    {value: 'Cyprus', name: 'Cyprus', id: 'CY'}, 
    {value: 'Czech Republic', name: 'Czech Republic', id: 'CZ'}, 
    {value: 'Denmark', name: 'Denmark', id: 'DK'}, 
    {value: 'Djibouti', name: 'Djibouti', id: 'DJ'}, 
    {value: 'Dominica', name: 'Dominica', id: 'DM'}, 
    {value: 'Dominican Republic', name: 'Dominican Republic', id: 'DO'}, 
    {value: 'Ecuador', name: 'Ecuador', id: 'EC'}, 
    // {value: 'Egypt', name: 'Egypt', id: 'EG'}, 
    {value: 'El Salvador', name: 'El Salvador', id: 'SV'}, 
    {value: 'Equatorial Guinea', name: 'Equatorial Guinea', id: 'GQ'}, 
    // {value: 'Eritrea', name: 'Eritrea', id: 'ER'}, 
    {value: 'Estonia', name: 'Estonia', id: 'EE'}, 
    {value: 'Ethiopia', name: 'Ethiopia', id: 'ET'}, 
    {value: 'Falkland Islands (Malvinas)', name: 'Falkland Islands (Malvinas)', id: 'FK'}, 
    {value: 'Faroe Islands', name: 'Faroe Islands', id: 'FO'}, 
    {value: 'Fiji', name: 'Fiji', id: 'FJ'}, 
    {value: 'Finland', name: 'Finland', id: 'FI'}, 
    {value: 'France', name: 'France', id: 'FR'}, 
    {value: 'French Guiana', name: 'French Guiana', id: 'GF'}, 
    {value: 'French Polynesia', name: 'French Polynesia', id: 'PF'}, 
    {value: 'French Southern Territories', name: 'French Southern Territories', id: 'TF'}, 
    {value: 'Gabon', name: 'Gabon', id: 'GA'}, 
    {value: 'Gambia', name: 'Gambia', id: 'GM'}, 
    {value: 'Georgia', name: 'Georgia', id: 'GE'}, 
    {value: 'Germany', name: 'Germany', id: 'DE'}, 
    {value: 'Ghana', name: 'Ghana', id: 'GH'}, 
    {value: 'Gibraltar', name: 'Gibraltar', id: 'GI'}, 
    {value: 'Greece', name: 'Greece', id: 'GR'}, 
    {value: 'Greenland', name: 'Greenland', id: 'GL'}, 
    {value: 'Grenada', name: 'Grenada', id: 'GD'}, 
    {value: 'Guadeloupe', name: 'Guadeloupe', id: 'GP'}, 
    {value: 'Guam', name: 'Guam', id: 'GU'}, 
    {value: 'Guatemala', name: 'Guatemala', id: 'GT'}, 
    {value: 'Guernsey', name: 'Guernsey', id: 'GG'}, 
    {value: 'Guinea', name: 'Guinea', id: 'GN'}, 
    // {value: 'Guinea-Bissau', name: 'Guinea-Bissau', id: 'GW'}, 
    {value: 'Guyana', name: 'Guyana', id: 'GY'}, 
    {value: 'Haiti', name: 'Haiti', id: 'HT'}, 
    {value: 'Heard Island and Mcdonald Islands', name: 'Heard Island and Mcdonald Islands', id: 'HM'}, 
    {value: 'Holy See (Vatican City State)', name: 'Holy See (Vatican City State)', id: 'VA'}, 
    {value: 'Honduras', name: 'Honduras', id: 'HN'}, 
    {value: 'Hong Kong', name: 'Hong Kong', id: 'HK'}, 
    {value: 'Hungary', name: 'Hungary', id: 'HU'}, 
    {value: 'Iceland', name: 'Iceland', id: 'IS'}, 
    {value: 'India', name: 'India', id: 'IN'}, 
    {value: 'Indonesia', name: 'Indonesia', id: 'ID'}, 
    // {value: 'Iran, Islamic Republic Of', name: 'Iran, Islamic Republic Of', id: 'IR'}, 
    // {value: 'Iraq', name: 'Iraq', id: 'IQ'}, 
    {value: 'Ireland', name: 'Ireland', id: 'IE'}, 
    {value: 'Isle of Man', name: 'Isle of Man', id: 'IM'}, 
    {value: 'Israel', name: 'Israel', id: 'IL'}, 
    {value: 'Italy', name: 'Italy', id: 'IT'}, 
    {value: 'Jamaica', name: 'Jamaica', id: 'JM'}, 
    {value: 'Japan', name: 'Japan', id: 'JP'}, 
    {value: 'Jersey', name: 'Jersey', id: 'JE'}, 
    {value: 'Jordan', name: 'Jordan', id: 'JO'}, 
    {value: 'Kazakhstan', name: 'Kazakhstan', id: 'KZ'}, 
    {value: 'Kenya', name: 'Kenya', id: 'KE'}, 
    {value: 'Kiribati', name: 'Kiribati', id: 'KI'}, 
    {name: 'Korea, Democratic People\'S Republic of', id: 'KP'}, 
    {value: 'Korea, Republic of', name: 'Korea, Republic of', id: 'KR'}, 
    {value: 'Kuwait', name: 'Kuwait', id: 'KW'}, 
    {value: 'Kyrgyzstan', name: 'Kyrgyzstan', id: 'KG'}, 
    {value: 'Lao People\'S Democratic Republic', name: 'Lao People\'S Democratic Republic', id: 'LA'}, 
    {value: 'Latvia', name: 'Latvia', id: 'LV'}, 
    // {value: 'Lebanon', name: 'Lebanon', id: 'LB'}, 
    {value: 'Lesotho', name: 'Lesotho', id: 'LS'}, 
    {value: 'Liberia', name: 'Liberia', id: 'LR'}, 
    // {value: 'Libyan Arab Jamahiriya', name: 'Libyan Arab Jamahiriya', id: 'LY'}, 
    {value: 'Liechtenstein', name: 'Liechtenstein', id: 'LI'}, 
    {value: 'Lithuania', name: 'Lithuania', id: 'LT'}, 
    {value: 'Luxembourg', name: 'Luxembourg', id: 'LU'}, 
    {value: 'Macao', name: 'Macao', id: 'MO'}, 
    {value: 'Macedonia, The Former Yugoslav Republic of', name: 'Macedonia, The Former Yugoslav Republic of', id: 'MK'}, 
    {value: 'Madagascar', name: 'Madagascar', id: 'MG'}, 
    {value: 'Malawi', name: 'Malawi', id: 'MW'}, 
    {value: 'Malaysia', name: 'Malaysia', id: 'MY'}, 
    {value: 'Maldives', name: 'Maldives', id: 'MV'}, 
    // {value: 'Mali', name: 'Mali', id: 'ML'}, 
    {value: 'Malta', name: 'Malta', id: 'MT'}, 
    {value: 'Marshall Islands', name: 'Marshall Islands', id: 'MH'}, 
    {value: 'Martinique', name: 'Martinique', id: 'MQ'}, 
    {value: 'Mauritania', name: 'Mauritania', id: 'MR'}, 
    {value: 'Mauritius', name: 'Mauritius', id: 'MU'}, 
    {value: 'Mayotte', name: 'Mayotte', id: 'YT'}, 
    {value: 'Mexico', name: 'Mexico', id: 'MX'}, 
    {value: 'Micronesia, Federated States of', name: 'Micronesia, Federated States of', id: 'FM'}, 
    {value: 'Moldova, Republic of', name: 'Moldova, Republic of', id: 'MD'}, 
    {value: 'Monaco', name: 'Monaco', id: 'MC'}, 
    {value: 'Mongolia', name: 'Mongolia', id: 'MN'}, 
    {value: 'Montserrat', name: 'Montserrat', id: 'MS'}, 
    {value: 'Morocco', name: 'Morocco', id: 'MA'}, 
    {value: 'Mozambique', name: 'Mozambique', id: 'MZ'}, 
    // {value: 'Myanmar', name: 'Myanmar', id: 'MM'}, 
    {value: 'Namibia', name: 'Namibia', id: 'NA'}, 
    {value: 'Nauru', name: 'Nauru', id: 'NR'}, 
    {value: 'Nepal', name: 'Nepal', id: 'NP'}, 
    {value: 'Netherlands', name: 'Netherlands', id: 'NL'}, 
    {value: 'Netherlands Antilles', name: 'Netherlands Antilles', id: 'AN'}, 
    {value: 'New Caledonia', name: 'New Caledonia', id: 'NC'}, 
    {value: 'New Zealand', name: 'New Zealand', id: 'NZ'}, 
    // {value: 'Nicaragua', name: 'Nicaragua', id: 'NI'}, 
    {value: 'Niger', name: 'Niger', id: 'NE'}, 
    {value: 'Nigeria', name: 'Nigeria', id: 'NG'}, 
    {value: 'Niue', name: 'Niue', id: 'NU'}, 
    {value: 'Norfolk Island', name: 'Norfolk Island', id: 'NF'}, 
    {value: 'Northern Mariana Islands', name: 'Northern Mariana Islands', id: 'MP'}, 
    {value: 'Norway', name: 'Norway', id: 'NO'}, 
    {value: 'Oman', name: 'Oman', id: 'OM'}, 
    {value: 'Pakistan', name: 'Pakistan', id: 'PK'}, 
    {value: 'Palau', name: 'Palau', id: 'PW'}, 
    {value: 'Palestinian Territory, Occupied', name: 'Palestinian Territory, Occupied', id: 'PS'}, 
    {value: 'Panama', name: 'Panama', id: 'PA'}, 
    {value: 'Papua New Guinea', name: 'Papua New Guinea', id: 'PG'}, 
    {value: 'Paraguay', name: 'Paraguay', id: 'PY'}, 
    {value: 'Peru', name: 'Peru', id: 'PE'}, 
    {value: 'Philippines', name: 'Philippines', id: 'PH'}, 
    {value: 'Pitcairn', name: 'Pitcairn', id: 'PN'}, 
    {value: 'Poland', name: 'Poland', id: 'PL'}, 
    {value: 'Portugal', name: 'Portugal', id: 'PT'}, 
    {value: 'Puerto Rico', name: 'Puerto Rico', id: 'PR'}, 
    {value: 'Qatar', name: 'Qatar', id: 'QA'}, 
    {value: 'Reunion', name: 'Reunion', id: 'RE'}, 
    {value: 'Romania', name: 'Romania', id: 'RO'}, 
    // {value: 'Russian Federation', name: 'Russian Federation', id: 'RU'}, 
    {value: 'RWANDA', name: 'RWANDA', id: 'RW'}, 
    {value: 'Saint Helena', name: 'Saint Helena', id: 'SH'}, 
    {value: 'Saint Kitts and Nevis', name: 'Saint Kitts and Nevis', id: 'KN'}, 
    {value: 'Saint Lucia', name: 'Saint Lucia', id: 'LC'}, 
    {value: 'Saint Pierre and Miquelon', name: 'Saint Pierre and Miquelon', id: 'PM'}, 
    {value: 'Saint Vincent and the Grenadines', name: 'Saint Vincent and the Grenadines', id: 'VC'}, 
    {value: 'Samoa', name: 'Samoa', id: 'WS'}, 
    {value: 'San Marino', name: 'San Marino', id: 'SM'}, 
    {value: 'Sao Tome and Principe', name: 'Sao Tome and Principe', id: 'ST'}, 
    {value: 'Saudi Arabia', name: 'Saudi Arabia', id: 'SA'}, 
    {value: 'Senegal', name: 'Senegal', id: 'SN'}, 
    {value: 'Serbia and Montenegro', name: 'Serbia and Montenegro', id: 'CS'}, 
    {value: 'Seychelles', name: 'Seychelles', id: 'SC'}, 
    {value: 'Sierra Leone', name: 'Sierra Leone', id: 'SL'}, 
    {value: 'Singapore', name: 'Singapore', id: 'SG'}, 
    {value: 'Slovakia', name: 'Slovakia', id: 'SK'}, 
    {value: 'Slovenia', name: 'Slovenia', id: 'SI'}, 
    {value: 'Solomon Islands', name: 'Solomon Islands', id: 'SB'}, 
    // {value: 'Somalia', name: 'Somalia', id: 'SO'}, 
    {value: 'South Africa', name: 'South Africa', id: 'ZA'}, 
    {value: 'South Georgia and the South Sandwich Islands', name: 'South Georgia and the South Sandwich Islands', id: 'GS'}, 
    {value: 'Spain', name: 'Spain', id: 'ES'}, 
    {value: 'Sri Lanka', name: 'Sri Lanka', id: 'LK'}, 
    {value: 'Sudan', name: 'Sudan', id: 'SD'}, 
    {value: 'Suriname', name: 'Suriname', id: 'SR'}, 
    {value: 'Svalbard and Jan Mayen', name: 'Svalbard and Jan Mayen', id: 'SJ'}, 
    {value: 'Swaziland', name: 'Swaziland', id: 'SZ'}, 
    {value: 'Sweden', name: 'Sweden', id: 'SE'}, 
    {value: 'Switzerland', name: 'Switzerland', id: 'CH'}, 
    // {value: 'Syrian Arab Republic', name: 'Syrian Arab Republic', id: 'SY'}, 
    {value: 'Taiwan, Province of China', name: 'Taiwan, Province of China', id: 'TW'}, 
    {value: 'Tajikistan', name: 'Tajikistan', id: 'TJ'}, 
    {value: 'Tanzania, United Republic of', name: 'Tanzania, United Republic of', id: 'TZ'}, 
    {value: 'Thailand', name: 'Thailand', id: 'TH'}, 
    {value: 'Timor-Leste', name: 'Timor-Leste', id: 'TL'}, 
    {value: 'Togo', name: 'Togo', id: 'TG'}, 
    {value: 'Tokelau', name: 'Tokelau', id: 'TK'}, 
    {value: 'Tonga', name: 'Tonga', id: 'TO'}, 
    {value: 'Trinidad and Tobago', name: 'Trinidad and Tobago', id: 'TT'}, 
    // {value: 'Tunisia', name: 'Tunisia', id: 'TN'}, 
    {value: 'Turkey', name: 'Turkey', id: 'TR'}, 
    {value: 'Turkmenistan', name: 'Turkmenistan', id: 'TM'}, 
    {value: 'Turks and Caicos Islands', name: 'Turks and Caicos Islands', id: 'TC'}, 
    {value: 'Tuvalu', name: 'Tuvalu', id: 'TV'}, 
    {value: 'Uganda', name: 'Uganda', id: 'UG'}, 
    {value: 'Ukraine', name: 'Ukraine', id: 'UA'}, 
    {value: 'United Arab Emirates', name: 'United Arab Emirates', id: 'AE'}, 
    {value: 'United Kingdom', name: 'United Kingdom', id: 'GB'}, 
    {value: 'United States', name: 'United States', id: 'US'}, 
    {value: 'United States Minor Outlying Islands', name: 'United States Minor Outlying Islands', id: 'UM'}, 
    {value: 'Uruguay', name: 'Uruguay', id: 'UY'}, 
    {value: 'Uzbekistan', name: 'Uzbekistan', id: 'UZ'}, 
    {value: 'Vanuatu', name: 'Vanuatu', id: 'VU'}, 
    // {value: 'Venezuela', name: 'Venezuela', id: 'VE'}, 
    {value: 'Viet Nam', name: 'Viet Nam', id: 'VN'}, 
    {value: 'Virgin Islands, British', name: 'Virgin Islands, British', id: 'VG'}, 
    {value: 'Virgin Islands, U.S.', name: 'Virgin Islands, U.S.', id: 'VI'}, 
    {value: 'Wallis and Futuna', name: 'Wallis and Futuna', id: 'WF'}, 
    {value: 'Western Sahara', name: 'Western Sahara', id: 'EH'}, 
    // {value: 'Yemen', name: 'Yemen', id: 'YE'}, 
    {value: 'Zambia', name: 'Zambia', id: 'ZM'}, 
    // {value: 'Zimbabwe', name: 'Zimbabwe', id: 'ZW'} 
  ]